name: Haus testing
on:
  push:
    branches: [main]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: gradle build

    - name: Run Api Testing
      run: gradle clean aggregate test --tests "runners.apis.UserRunner" -DbaseUrl=https://reqres.in/
      
  
